import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/navbar";
import Provider from "@/components/provider";

const merriweather = Merriweather({
	weight: ["300", "400", "700", "900"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Vincent Mukuna",

	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`bg-slate-50 dark:bg-[#040D12] dark:text-white transition-colors`}
			>
				<Provider>
					<Navbar />
					{children}
				</Provider>
			</body>
		</html>
	);
}
